# .github/workflows/deploy.yml

name: Google Cloud Project Deploy

on:
  push:
    branches:
      - release

env:
  PROJECT_ID: price-finder-test
  SERVICE: get-prediction
  REGION: asia-south1

jobs:

  deploy:
    name: github actions test
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0
        with:
          # Value recieved from step 7 in Setting up Workload Identity Federation
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Run Cloud Build
        run: |-
          gcloud builds submit

      - name: Deploy to Cloud Run

        uses: google-github-actions/deploy-cloudrun@v0

        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}

